### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [HuimengLu/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] #2
  - e.g., https://code.visualstudio.com/ , https://sdacs.ucsd.edu/~icc/index.php , etc. 
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - I noticed the titles are all numbered as 1, could you try fixing that so they're numbered 1-6
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - please also show the terminal output of the command you came up with to optimize running files remotely from your computer
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by farnaf** [comment]
Thanks for submitting a regrade request!

Second to last requirement is not quite complete yet. What we're looking for is a command in your local terminal that runs the java program on the server (the computer you access when you ssh with your 15L account).

To do the above task the long way, we can (1) use scp to copy the java file over to the server (2) ssh into 15L account (3) compile the copied java file (4) run it. The goal of the last step is to come up with an optimized version of these 4 steps.

Let me know if you have any questions!

**Comment by HuimengLu** [comment]
Hi! I have updated my lab report according to your comments. Could you please check if the last part is completed yet? Thank you!

**Comment by farnaf** [comment]
Great! Could you make a new regrade request on Gradescope?
